### ISSUE TITLE
Fleets are always hidden

### ISSUE THREAD

**Issue by nyuszika7h** [haoict/twitter-no-ads#13] opened 2021-03-06 11:00 UTC
If I have "No Fleets" disabled, it still hides fleets from people I follow, it only shows my own fleets in the bar.

**Comment by haoict** [comment] 2021-03-26 00:30
Sorry I couldn't reproduce the issue.
I tried turn off that option and I can see other people fleets without any problem.
Probably that time you didn't have any fleet from people.
I'll close this for now. Feel free to reopen the issue.

**Closed by haoict** 2021-03-26 00:30 UTC

**Comment by nyuszika7h** [comment] 2021-03-26 01:16
I doubt that since I follow like 800 people on that account, but now I can't reproduce anymore either.
